### ISSUE TITLE
No retry if opening the the event stream fails first time

### ISSUE THREAD

**Issue by danielrohe** [zalando-incubator/fahrschein#124]
The first call to openJsonInput in NakadiReader#runInternal is not in the retry-loop. So if this fails there won't be a retry.

**Comment by tmuehl** [comment]
@jhorstmann Can we distinguish between client and nakadi side errors? Then I'd say retrying in case it's not a `4xx` is fine.

**Comment by lukasniemeier-zalando** [comment]
We can do something similar like riptide does, see https://github.com/zalando/riptide/blob/master/riptide-exceptions/src/main/java/org/zalando/riptide/exceptions/ExceptionClassifier.java#L38

**Comment by jhorstmann** [comment]
> We can do something similar like riptide does

That list of exceptions seems really arbitrary.

> Can we distinguish between client and nakadi side errors?

There are two cases that we might want to handle differently.

 - The connection to nakadi itself could not be established on the first try
 - The connection could be established, but the first batch of events does not arrive before the read timeout. The status line and headers probably did arrive in time.

I don't know how the second case could happen, except for a bug in nakadi itself. Retrying the second case would make sense, assuming it only happens if we would really receive an event batch. Retrying in case of authorization or scope errors would not make sense, but it is very unlikey we would get a read timeout for that.

Disabling encoding autodetection as proposed in in #37 and #123 would solve the second case.

@danielrohe Do you agree with the above scenarios?

**Comment by danielrohe** [comment]
The first case is the common connect timeout where nakadi itself is not reachable and the second is the read timeout case where the response is not returned in time.

Retrying the cases depends on whether the fahrschein client functionality includes retrying until the user stops it. It should be clearly stated whether the fahrschein reader handles the retry on error or whether users of the library have to handle this.

**Comment by jhorstmann** [comment]
> It should be clearly stated whether the fahrschein reader handles the retry on error or whether users of the library have to handle this.

So this is more a documentation issue at the moment?

**Comment by danielrohe** [comment]
Yes, if you state that fahrschein reader should handle this, then both cases should be covered, if not then I would expect the fahrschein reader to stop on any network or serialization issue and let the users of the fahrschein reader handle this problem

**Comment by jhorstmann** [comment]
Fixed by #129
