### ISSUE TITLE
Support subscription for multiple events  

### ISSUE THREAD

**Issue by AdnanKukuljac** [zalando-incubator/fahrschein#142]
It would be really helpful if _fahrschein_ could provide subscription for multiple events. 

e.g. 
`Subscription subscribe(String applicationName, Set<String> eventTypes, String consumerGroup)`

Benefits:
https://github.com/zalando/nakadi#client-rebalancing

**Comment by jhorstmann** [comment]
Some thoughts about required changes:

 - [ ] `NakadiReader` needs to use `eventName` from cursor instead of it's property for reporting to `CursorManager`
 - [ ] Log messages in `NakadiReader` need to be modified to either not include the event name or include all events
 - [ ] `CursorManager` is based on the the event name, `ManagedCursorManager` `addSubscription` and `addStreamId` would have to add entries for all event names.
 - [ ] It might be required to add multiple listeners in `SubscriptionStreamBuilder`, so that `NakadiReader` can call the correct listener depending on the event type of the batch

**Comment by jhorstmann** [comment]
Fixed by #144
