### ISSUE TITLE
Local stream timeout does not trigger reconnection

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-incubator/fahrschein#28]
Currently `StreamParameters#getStreamTimout` is used for a local timeout in `NakadiReader` (`while`-loop). Does this make sense?

Also consider adding a log statement if `while` loop exists.

**Comment by jhorstmann** [comment]
The idea was to also implement the stream parameters locally, so after a certain number of events/time/batches the connection gets closed and reopened.

But there should also be support for locking partitions so that only one node can read from them at a time. These locks should have a defined timeout, after which another node can grab the lock without it being explicitly released. To support this the `NakadiReader` should stop reading just before the lock expires and try to reacquire the lock.

**Comment by jhorstmann** [comment]
Fixed by #50
